baseURL = "https://tonybox.net/"
languageCode = "en-us"
title = "tonybox.net"
disqusShortname = "tonybox"
pygmentsUseClasses = true
enableRobotsTXT = true

[params]
   author = "Anthony Biondo"
   description = "Anthony Biondo is a tech lawyer in NYC, who sometimes writes about technology, security, and maybe even the law."
